### ISSUE TITLE
Error `n is null` when trying to use the library in browser

### ISSUE THREAD

**Issue by ikariiin** [aeroheim/midori#6]
Repro CodeSandbox: https://codesandbox.io/s/laughing-germain-4kpjy

Throws this error error from the file `/node_modules/midori-bg/dist/midori.js`:
```
n is null
```

**Comment by aeroheim** [comment]
In your sandbox you aren't correctly querying the canvas element so you are passing `null` to the `BackgroundRenderer`. 

I found another issue after fixing that when calling `setImage` without a transition - I'll publish a new version of the package with the fix shortly.

**Comment by aeroheim** [comment]
This should work correctly now in 0.6.1 - I forked and updated your [sandbox](https://codesandbox.io/s/summer-dream-k9vl5) and it looks like it works.

**Comment by ikariiin** [comment]
Aah! Seems like it does indeed work now!

Thanks for the quick response!
